extends:
  - stylelint-config-recommended-scss
  - stylelint-config-property-sort-order-smacss
  - stylelint-config-sass-guidelines
plugins:
  - stylelint-scss
rules:
  function-parentheses-space-inside: null
  max-empty-lines: 1
  max-nesting-depth: null
  no-empty-source: null
  order/properties-order: null
  scss/dollar-variable-pattern: null
  scss/no-global-function-names: null
  selector-class-pattern: null
  selector-max-compound-selectors: null
  selector-pseudo-element-no-unknown: null
  selector-no-qualifying-type: null
